version: '3'

services:
  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: ghcr.io/xmtp/grafana-xmtpd:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
