version: '3'

services:
  pushgateway:
    image: prom/pushgateway:latest
    pull_policy: always
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:latest
    pull_policy: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: ghcr.io/xmtp/grafana-xmtpd:latest
    pull_policy: always
    ports:
      - "3000:3000"